# Generated by Django 4.0.6 on 2022-08-06 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(default='/Users/ahmadcoded/Development/project/Travel_App/backend_repo/media/images/Simulator_Screen_Shot_-_iPhone_13_Pro_Max_-_2022-06-22_at_17.46.04.png', upload_to='images')),
                ('country', models.CharField(default='', max_length=100)),
                ('like', models.BooleanField(default=False)),
                ('wants_to_visit', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('avatar', models.ImageField(default='/Users/ahmadcoded/Development/project/Travel_App/backend_repo/media/images/Simulator_Screen_Shot_-_iPhone_13_Pro_Max_-_2022-06-22_at_17.46.04.png', upload_to='images')),
                ('list_of_trips', models.ManyToManyField(blank=True, to='trip.trip')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
