# Generated by Django 4.0.6 on 2022-08-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, default='/Users/ahmadcoded/Development/project/Travel_App/backend_repo/media/images/Simulator_Screen_Shot_-_iPhone_13_Pro_Max_-_2022-06-22_at_17.46.04.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='wants_to_visit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
